version: '3'

services: 

  myapp:
    image: bgastaldi/myapp
    container_name: myapp
    hostname: myapp
    networks: 
      - wpp-network
    tty: true
       
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8080:8080" #php-client
    networks: 
      - wpp-network
    depends_on:
      - myapp

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 